### PR TITLE
Update Azure Cosmos SDK to track 2

### PR DESCRIPTION
**Pull request by zzhxiaofeng**
1. Upgrade Azure Cosmos SDK to track 2.
2. Updated files:
    i. load_materialized_views.js
   ii. webapp/dao/cosmosdb_dao.js
  iii. webapp/package-lock.json
  iv. webapp/package.json
   v. webapp/routes/bom.js
  vi. webapp/routes/library.js
 vii. webapp/routes/maintainer.js
viii. package-lock.json
  ix. package.json

@lilyjma, @ramya-rao-a, @meeraharidasa, @mayurid, @southpolesteve and @jongio for notification.

### CODE REVIEW

**Comment by ramya-rao-a** [comment]
@zfoster Can you review this please?

**Comment by v-xuto** [comment]
@lilyjma, @ramya-rao-a, @kyle-patterson, @mayurid, @dw511214992 
Could you please review this PR？

**Comment by ramya-rao-a** [comment]
@cjoakim, Looks like you have a few commits into this repo. Can you help with the review here?

**Review by johncastorina — APPROVED** [review]

**Comment by cjoakim** [comment]
@zzhxiaofeng - there are now conflicts in this PR after the dependabot PRs have been merged.  Could you please recreate and resubmit your PR based on the latest code in master?   thank you.

**Pull request merged**
